In [3]:
pip install nltk

Requirement already satisfied: nltk in c:\users\aamir\anaconda3\lib\site-packages (3.6.7)
Requirement already satisfied: tqdm in c:\users\aamir\anaconda3\lib\site-packages (from nltk) (4.62.3)
Requirement already satisfied: regex>=2021.8.3 in c:\users\aamir\anaconda3\lib\site-packages (from nltk) (2021.11.10)
Requirement already satisfied: joblib in c:\users\aamir\anaconda3\lib\site-packages (from nltk) (1.1.0)
Requirement already satisfied: click in c:\users\aamir\anaconda3\lib\site-packages (from nltk) (8.0.3)
Requirement already satisfied: colorama in c:\users\aamir\anaconda3\lib\site-packages (from click->nltk) (0.4.4)
Note: you may need to restart the kernel to use updated packages.

In [4]:
import nltk
nltk.download()

showing info https://raw.githubusercontent.com/nltk/nltk_data/gh-pages/index.xml

True

In [5]:
import pandas as pd

In [6]:
fake = pd.read_csv("Fake-news.csv")
geniune = pd.read_csv("True-news.csv")

C:\Users\Aamir\anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3444: DtypeWarning: Columns (4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,92,93,94,95,96,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,123,124,125,126,127,128,129,130,131,132,133,134,135,136,137,138,139,140,141,142,143,144,145,146,147,148,149,150,151,152,153,154,155,156,157,158,159,160,161,162,163,164,165,166,167,168,169,170,171) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

In [7]:
display(fake.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23502 entries, 0 to 23501
Columns: 172 entries, title to Unnamed: 171
dtypes: object(172)
memory usage: 30.8+ MB

None

In [8]:
display(geniune.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21417 entries, 0 to 21416
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   title    21417 non-null  object
 1   text     21417 non-null  object
 2   subject  21417 non-null  object
 3   date     21417 non-null  object
dtypes: object(4)
memory usage: 669.4+ KB

None

In [9]:
display(fake.head())

,title,text,subject,date,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 162,Unnamed: 163,Unnamed: 164,Unnamed: 165,Unnamed: 166,Unnamed: 167,Unnamed: 168,Unnamed: 169,Unnamed: 170,Unnamed: 171
0,Donald Trump Sends Out Embarrassing New Year’...,Donald Trump just couldn t wish all Americans ...,News,"December 31, 2017",NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Drunk Bragging Trump Staffer Started Russian ...,House Intelligence Committee Chairman Devin Nu...,News,"December 31, 2017",NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Sheriff David Clarke Becomes An Internet Joke...,"On Friday, it was revealed that former Milwauk...",News,"December 30, 2017",NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Trump Is So Obsessed He Even Has Obama’s Name...,"On Christmas day, Donald Trump announced that ...",News,"December 29, 2017",NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Pope Francis Just Called Out Donald Trump Dur...,Pope Francis used his annual Christmas Day mes...,News,"December 25, 2017",NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [10]:
display(geniune.head(10))

,title,text,subject,date
0,"As U.S. budget fight looms, Republicans flip t...",WASHINGTON (Reuters) - The head of a conservat...,politicsNews,"December 31, 2017"
1,U.S. military to accept transgender recruits o...,WASHINGTON (Reuters) - Transgender people will...,politicsNews,"December 29, 2017"
2,Senior U.S. Republican senator: 'Let Mr. Muell...,WASHINGTON (Reuters) - The special counsel inv...,politicsNews,"December 31, 2017"
3,FBI Russia probe helped by Australian diplomat...,WASHINGTON (Reuters) - Trump campaign adviser ...,politicsNews,"December 30, 2017"
4,Trump wants Postal Service to charge 'much mor...,SEATTLE/WASHINGTON (Reuters) - President Donal...,politicsNews,"December 29, 2017"
5,"White House, Congress prepare for talks on spe...","WEST PALM BEACH, Fla./WASHINGTON (Reuters) - T...",politicsNews,"December 29, 2017"
6,"Trump says Russia probe will be fair, but time...","WEST PALM BEACH, Fla (Reuters) - President Don...",politicsNews,"December 29, 2017"
7,Factbox: Trump on Twitter (Dec 29) - Approval ...,The following statements were posted to the ve...,politicsNews,"December 29, 2017"
8,Trump on Twitter (Dec 28) - Global Warming,The following statements were posted to the ve...,politicsNews,"December 29, 2017"
9,Alabama official to certify Senator-elect Jone...,WASHINGTON (Reuters) - Alabama Secretary of St...,politicsNews,"December 28, 2017"

In [11]:
display(fake.subject.value_counts())

News                                                                                                                                                                                                                                                                                            9050
politics                                                                                                                                                                                                                                                                                        6838
left-news                                                                                                                                                                                                                                                                                       4457
Government News                                                                                                                                                                                                                                                                                 1570
US_News                                                                                                                                                                                                                                                                                          775
Middle-east                                                                                                                                                                                                                                                                                      770
 high taxes                                                                                                                                                                                                                                                                                        2
 claimed that hundreds of alternative media websites were producing  fake news  and  conspiracy  stories and therefore were unreliable as information sources. It wasn t long before the establishment began referencing these politicized lists                                                   2
 of which Soros is a major financier.Mercy Corps: Vis a vis the Arab-Israeli conflict                                                                                                                                                                                                              2
 and so is Mr. Katzenbach                                                                                                                                                                                                                                                                          2
 fell 5.6 percent Monday. Wynn Resortsslipped 1.2 percent. Las Vegas Sands fell as much as 2.1 percent before closing higher.   LIVE DRILL    Las Vegas has been at the forefront of active shooter training. ( Image Source: sinclairstoryline)Las Vegas Active Shooter Drills Back in 2014       2
 state systems with outsized pretensions to power have reacted to their environments in two ways. The first strategy                                                                                                                                                                               2
 decided not to seek re-election. While much of the mainstream media waxed poetic about his 30-year career                                                                                                                                                                                         2
 the defense industry                                                                                                                                                                                                                                                                              2
 Karl Marx is either a villain or a hero of social engineering                                                                                                                                                                                                                                     2
 a future nuclear family                                                                                                                                                                                                                                                                           2
 Politics According to the Bible and (with Barry Asmus) The Poverty of Nations: A Sustainable Solution.Via: Townhall"                                                                                                                                                                              1
Name: subject, dtype: int64

In [12]:
fake['target']=0
geniune['target']=1

In [13]:
display(geniune.head(10))

,title,text,subject,date,target
0,"As U.S. budget fight looms, Republicans flip t...",WASHINGTON (Reuters) - The head of a conservat...,politicsNews,"December 31, 2017",1
1,U.S. military to accept transgender recruits o...,WASHINGTON (Reuters) - Transgender people will...,politicsNews,"December 29, 2017",1
2,Senior U.S. Republican senator: 'Let Mr. Muell...,WASHINGTON (Reuters) - The special counsel inv...,politicsNews,"December 31, 2017",1
3,FBI Russia probe helped by Australian diplomat...,WASHINGTON (Reuters) - Trump campaign adviser ...,politicsNews,"December 30, 2017",1
4,Trump wants Postal Service to charge 'much mor...,SEATTLE/WASHINGTON (Reuters) - President Donal...,politicsNews,"December 29, 2017",1
5,"White House, Congress prepare for talks on spe...","WEST PALM BEACH, Fla./WASHINGTON (Reuters) - T...",politicsNews,"December 29, 2017",1
6,"Trump says Russia probe will be fair, but time...","WEST PALM BEACH, Fla (Reuters) - President Don...",politicsNews,"December 29, 2017",1
7,Factbox: Trump on Twitter (Dec 29) - Approval ...,The following statements were posted to the ve...,politicsNews,"December 29, 2017",1
8,Trump on Twitter (Dec 28) - Global Warming,The following statements were posted to the ve...,politicsNews,"December 29, 2017",1
9,Alabama official to certify Senator-elect Jone...,WASHINGTON (Reuters) - Alabama Secretary of St...,politicsNews,"December 28, 2017",1

In [14]:
display(fake.head(10))

,title,text,subject,date,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 163,Unnamed: 164,Unnamed: 165,Unnamed: 166,Unnamed: 167,Unnamed: 168,Unnamed: 169,Unnamed: 170,Unnamed: 171,target
0,Donald Trump Sends Out Embarrassing New Year’...,Donald Trump just couldn t wish all Americans ...,News,"December 31, 2017",NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
1,Drunk Bragging Trump Staffer Started Russian ...,House Intelligence Committee Chairman Devin Nu...,News,"December 31, 2017",NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
2,Sheriff David Clarke Becomes An Internet Joke...,"On Friday, it was revealed that former Milwauk...",News,"December 30, 2017",NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
3,Trump Is So Obsessed He Even Has Obama’s Name...,"On Christmas day, Donald Trump announced that ...",News,"December 29, 2017",NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
4,Pope Francis Just Called Out Donald Trump Dur...,Pope Francis used his annual Christmas Day mes...,News,"December 25, 2017",NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
5,Racist Alabama Cops Brutalize Black Boy While...,The number of cases of cops brutalizing and ki...,News,"December 25, 2017",NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
6,"Fresh Off The Golf Course, Trump Lashes Out A...",Donald Trump spent a good portion of his day a...,News,"December 23, 2017",NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
7,Trump Said Some INSANELY Racist Stuff Inside ...,In the wake of yet another court decision that...,News,"December 23, 2017",NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
8,Former CIA Director Slams Trump Over UN Bully...,Many people have raised the alarm regarding th...,News,"December 22, 2017",NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
9,WATCH: Brand-New Pro-Trump Ad Features So Muc...,Just when you might have thought we d get a br...,News,"December 21, 2017",NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0

In [14]:
data = pd.concat([fake,geniune],axis=0)

In [15]:
data=data.reset_index(drop=True)

In [16]:
data=data.drop(['subject','date','title'],axis=1)

In [17]:
print(data.columns)

Index(['text', 'Unnamed: 4', 'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7',
       'Unnamed: 8', 'Unnamed: 9', 'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12',
       ...
       'Unnamed: 163', 'Unnamed: 164', 'Unnamed: 165', 'Unnamed: 166',
       'Unnamed: 167', 'Unnamed: 168', 'Unnamed: 169', 'Unnamed: 170',
       'Unnamed: 171', 'target'],
      dtype='object', length=170)

In [20]:
from nltk.tokenize import word_tokenize

In [21]:
data['text']=data['text'].apply(word_tokenize)

In [22]:
print(data.head(10))

                                                text Unnamed: 4 Unnamed: 5  \
0  [Donald, Trump, just, couldn, t, wish, all, Am...        NaN        NaN
1  [House, Intelligence, Committee, Chairman, Dev...        NaN        NaN
2  [On, Friday, ,, it, was, revealed, that, forme...        NaN        NaN
3  [On, Christmas, day, ,, Donald, Trump, announc...        NaN        NaN
4  [Pope, Francis, used, his, annual, Christmas, ...        NaN        NaN
5  [The, number, of, cases, of, cops, brutalizing...        NaN        NaN
6  [Donald, Trump, spent, a, good, portion, of, h...        NaN        NaN
7  [In, the, wake, of, yet, another, court, decis...        NaN        NaN
8  [Many, people, have, raised, the, alarm, regar...        NaN        NaN
9  [Just, when, you, might, have, thought, we, d,...        NaN        NaN

  Unnamed: 6 Unnamed: 7 Unnamed: 8 Unnamed: 9 Unnamed: 10 Unnamed: 11  \
0        NaN        NaN        NaN        NaN         NaN         NaN
1        NaN        NaN        NaN        NaN         NaN         NaN
2        NaN        NaN        NaN        NaN         NaN         NaN
3        NaN        NaN        NaN        NaN         NaN         NaN
4        NaN        NaN        NaN        NaN         NaN         NaN
5        NaN        NaN        NaN        NaN         NaN         NaN
6        NaN        NaN        NaN        NaN         NaN         NaN
7        NaN        NaN        NaN        NaN         NaN         NaN
8        NaN        NaN        NaN        NaN         NaN         NaN
9        NaN        NaN        NaN        NaN         NaN         NaN

  Unnamed: 12  ... Unnamed: 163 Unnamed: 164 Unnamed: 165 Unnamed: 166  \
0         NaN  ...          NaN          NaN          NaN          NaN
1         NaN  ...          NaN          NaN          NaN          NaN
2         NaN  ...          NaN          NaN          NaN          NaN
3         NaN  ...          NaN          NaN          NaN          NaN
4         NaN  ...          NaN          NaN          NaN          NaN
5         NaN  ...          NaN          NaN          NaN          NaN
6         NaN  ...          NaN          NaN          NaN          NaN
7         NaN  ...          NaN          NaN          NaN          NaN
8         NaN  ...          NaN          NaN          NaN          NaN
9         NaN  ...          NaN          NaN          NaN          NaN

  Unnamed: 167 Unnamed: 168 Unnamed: 169 Unnamed: 170 Unnamed: 171 target
0          NaN          NaN          NaN          NaN          NaN      0
1          NaN          NaN          NaN          NaN          NaN      0
2          NaN          NaN          NaN          NaN          NaN      0
3          NaN          NaN          NaN          NaN          NaN      0
4          NaN          NaN          NaN          NaN          NaN      0
5          NaN          NaN          NaN          NaN          NaN      0
6          NaN          NaN          NaN          NaN          NaN      0
7          NaN          NaN          NaN          NaN          NaN      0
8          NaN          NaN          NaN          NaN          NaN      0
9          NaN          NaN          NaN          NaN          NaN      0

[10 rows x 170 columns]

### STEMMING

In [24]:
from nltk.stem.snowball import SnowballStemmer
porter = SnowballStemmer("english")

In [25]:
def stem_it(text):
    return [porter.stem(word) for word in text]

In [26]:
data['text']=data['text'].apply(stem_it)

In [29]:
print(data.head(10))

                                                text Unnamed: 4 Unnamed: 5  \
0  [donald, trump, just, couldn, t, wish, all, am...        NaN        NaN
1  [hous, intellig, committe, chairman, devin, nu...        NaN        NaN
2  [on, friday, ,, it, was, reveal, that, former,...        NaN        NaN
3  [on, christma, day, ,, donald, trump, announc,...        NaN        NaN
4  [pope, franci, use, his, annual, christma, day...        NaN        NaN
5  [the, number, of, case, of, cop, brutal, and, ...        NaN        NaN
6  [donald, trump, spent, a, good, portion, of, h...        NaN        NaN
7  [in, the, wake, of, yet, anoth, court, decis, ...        NaN        NaN
8  [mani, peopl, have, rais, the, alarm, regard, ...        NaN        NaN
9  [just, when, you, might, have, thought, we, d,...        NaN        NaN

  Unnamed: 6 Unnamed: 7 Unnamed: 8 Unnamed: 9 Unnamed: 10 Unnamed: 11  \
0        NaN        NaN        NaN        NaN         NaN         NaN
1        NaN        NaN        NaN        NaN         NaN         NaN
2        NaN        NaN        NaN        NaN         NaN         NaN
3        NaN        NaN        NaN        NaN         NaN         NaN
4        NaN        NaN        NaN        NaN         NaN         NaN
5        NaN        NaN        NaN        NaN         NaN         NaN
6        NaN        NaN        NaN        NaN         NaN         NaN
7        NaN        NaN        NaN        NaN         NaN         NaN
8        NaN        NaN        NaN        NaN         NaN         NaN
9        NaN        NaN        NaN        NaN         NaN         NaN

  Unnamed: 12  ... Unnamed: 163 Unnamed: 164 Unnamed: 165 Unnamed: 166  \
0         NaN  ...          NaN          NaN          NaN          NaN
1         NaN  ...          NaN          NaN          NaN          NaN
2         NaN  ...          NaN          NaN          NaN          NaN
3         NaN  ...          NaN          NaN          NaN          NaN
4         NaN  ...          NaN          NaN          NaN          NaN
5         NaN  ...          NaN          NaN          NaN          NaN
6         NaN  ...          NaN          NaN          NaN          NaN
7         NaN  ...          NaN          NaN          NaN          NaN
8         NaN  ...          NaN          NaN          NaN          NaN
9         NaN  ...          NaN          NaN          NaN          NaN

  Unnamed: 167 Unnamed: 168 Unnamed: 169 Unnamed: 170 Unnamed: 171 target
0          NaN          NaN          NaN          NaN          NaN      0
1          NaN          NaN          NaN          NaN          NaN      0
2          NaN          NaN          NaN          NaN          NaN      0
3          NaN          NaN          NaN          NaN          NaN      0
4          NaN          NaN          NaN          NaN          NaN      0
5          NaN          NaN          NaN          NaN          NaN      0
6          NaN          NaN          NaN          NaN          NaN      0
7          NaN          NaN          NaN          NaN          NaN      0
8          NaN          NaN          NaN          NaN          NaN      0
9          NaN          NaN          NaN          NaN          NaN      0

[10 rows x 170 columns]

### STOPWORD REMOVAL

In [27]:
#from nltk.corpus import stopwords

In [30]:
def stop_it(t):
    dt=[word for word in t if len(word)>2]
    return dt

In [31]:
data['text']=data['text'].apply(stop_it)

In [32]:
print(data.head(10))

                                                text Unnamed: 4 Unnamed: 5  \
0  [donald, trump, just, couldn, wish, all, ameri...        NaN        NaN
1  [hous, intellig, committe, chairman, devin, nu...        NaN        NaN
2  [friday, was, reveal, that, former, milwauke, ...        NaN        NaN
3  [christma, day, donald, trump, announc, that, ...        NaN        NaN
4  [pope, franci, use, his, annual, christma, day...        NaN        NaN
5  [the, number, case, cop, brutal, and, kill, pe...        NaN        NaN
6  [donald, trump, spent, good, portion, his, day...        NaN        NaN
7  [the, wake, yet, anoth, court, decis, that, de...        NaN        NaN
8  [mani, peopl, have, rais, the, alarm, regard, ...        NaN        NaN
9  [just, when, you, might, have, thought, get, b...        NaN        NaN

  Unnamed: 6 Unnamed: 7 Unnamed: 8 Unnamed: 9 Unnamed: 10 Unnamed: 11  \
0        NaN        NaN        NaN        NaN         NaN         NaN
1        NaN        NaN        NaN        NaN         NaN         NaN
2        NaN        NaN        NaN        NaN         NaN         NaN
3        NaN        NaN        NaN        NaN         NaN         NaN
4        NaN        NaN        NaN        NaN         NaN         NaN
5        NaN        NaN        NaN        NaN         NaN         NaN
6        NaN        NaN        NaN        NaN         NaN         NaN
7        NaN        NaN        NaN        NaN         NaN         NaN
8        NaN        NaN        NaN        NaN         NaN         NaN
9        NaN        NaN        NaN        NaN         NaN         NaN

  Unnamed: 12  ... Unnamed: 163 Unnamed: 164 Unnamed: 165 Unnamed: 166  \
0         NaN  ...          NaN          NaN          NaN          NaN
1         NaN  ...          NaN          NaN          NaN          NaN
2         NaN  ...          NaN          NaN          NaN          NaN
3         NaN  ...          NaN          NaN          NaN          NaN
4         NaN  ...          NaN          NaN          NaN          NaN
5         NaN  ...          NaN          NaN          NaN          NaN
6         NaN  ...          NaN          NaN          NaN          NaN
7         NaN  ...          NaN          NaN          NaN          NaN
8         NaN  ...          NaN          NaN          NaN          NaN
9         NaN  ...          NaN          NaN          NaN          NaN

  Unnamed: 167 Unnamed: 168 Unnamed: 169 Unnamed: 170 Unnamed: 171 target
0          NaN          NaN          NaN          NaN          NaN      0
1          NaN          NaN          NaN          NaN          NaN      0
2          NaN          NaN          NaN          NaN          NaN      0
3          NaN          NaN          NaN          NaN          NaN      0
4          NaN          NaN          NaN          NaN          NaN      0
5          NaN          NaN          NaN          NaN          NaN      0
6          NaN          NaN          NaN          NaN          NaN      0
7          NaN          NaN          NaN          NaN          NaN      0
8          NaN          NaN          NaN          NaN          NaN      0
9          NaN          NaN          NaN          NaN          NaN      0

[10 rows x 170 columns]

In [33]:
data['text']=data['text'].apply(' '.join)

### SPLITTING

In [34]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(data['text'],data['target'])
display(X_train.head())
print('\n')
display(y_train.head())

28976    washington reuter presid donald trump nation s...
19185    june 2016 over 10,000 migrant came itali via b...
41647    barcelona reuter catalan leader carl puigdemon...
4164     donald trump has been come apart the seam befo...
20569    interest how much vitriol some women harbor fo...
Name: text, dtype: object

28976    1
19185    0
41647    1
4164     0
20569    0
Name: target, dtype: int64

### VECTORIZATION

In [36]:
from sklearn.feature_extraction.text import TfidfVectorizer
my_tfidf = TfidfVectorizer(max_df=0.7)

tfidf_train = my_tfidf.fit_transform(X_train)
tfidf_test = my_tfidf.transform(X_test)

In [37]:
print(tfidf_train)

  (0, 7654)	0.11653959826307421
  (0, 57101)	0.12267755684942584
  (0, 22362)	0.15376398138339942
  (0, 77444)	0.14357930305216746
  (0, 19593)	0.1251604408567445
  (0, 13562)	0.13508912660262626
  (0, 37753)	0.10904278359760114
  (0, 88899)	0.058859659969627796
  (0, 45808)	0.31793064635361123
  (0, 45771)	0.2448294062450973
  (0, 34437)	0.11611694289950744
  (0, 69613)	0.17691590240392738
  (0, 39756)	0.08771666092812584
  (0, 88834)	0.0957498202758773
  (0, 60298)	0.09627357350653015
  (0, 82417)	0.11602637503662747
  (0, 13580)	0.09166516239618903
  (0, 60309)	0.19041748943896916
  (0, 71369)	0.13246030906619116
  (0, 21853)	0.1659643148831682
  (0, 39041)	0.0599414900862525
  (0, 7356)	0.06538345963689136
  (0, 21957)	0.15759868970233387
  (0, 67550)	0.21748955297252184
  (0, 54327)	0.24753984994788766
  :	:
  (33688, 30049)	0.045390038590918565
  (33688, 81476)	0.019594206778965405
  (33688, 51178)	0.032749126031372255
  (33688, 13476)	0.02984052777828661
  (33688, 38951)	0.030238613975964123
  (33688, 69539)	0.05673692979562669
  (33688, 17190)	0.04118022323636498
  (33688, 18882)	0.04811525917200558
  (33688, 10371)	0.06415965798034744
  (33688, 17612)	0.028443659112148075
  (33688, 68767)	0.04801756864303271
  (33688, 10763)	0.0412235428678091
  (33688, 81397)	0.021874644878657045
  (33688, 8230)	0.05996910297986544
  (33688, 11228)	0.03406573218519613
  (33688, 48372)	0.028726782663779704
  (33688, 39418)	0.04320109180530882
  (33688, 65535)	0.05400013937356757
  (33688, 59281)	0.01880336008103652
  (33688, 44797)	0.05707880917418305
  (33688, 37890)	0.01874303419667668
  (33688, 86768)	0.03188446516783535
  (33688, 39041)	0.0206674333192163
  (33688, 58459)	0.046502066203600624
  (33688, 83333)	0.02311016158683504

### LOGISTIC REGRESSION

In [40]:
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score

In [41]:
model_1 = LogisticRegression(max_iter=900)
model_1.fit(tfidf_train,y_train)
pred_1 = model_1.predict(tfidf_test)
cr1 = accuracy_score(y_test,pred_1)
print(cr1*100)

98.81567230632236

### PASSIVE AGGRESSICE CLASSIFIER

In [45]:
from sklearn.linear_model import PassiveAggressiveClassifier

model = PassiveAggressiveClassifier(max_iter=50)
model.fit(tfidf_train,y_train)

PassiveAggressiveClassifier(max_iter=50)

In [46]:
y_pred = model.predict(tfidf_test)
accscore = accuracy_score(y_test,y_pred)
print('The accuracy of prediction is ',accscore*100)

The accuracy of prediction is  99.60819234194122